{% set name = "datasette-search-all" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e2a5eb5ac3e191364f69dc775fc233bbc754eec95d774462ec5ac2ba61eea86d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - datasette >=0.63.1

test:
  imports:
    - datasette_search_all
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simonw/datasette-search-all
  summary: Datasette plugin for searching all searchable tables at once
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
